### ISSUE TITLE
Can't connect UART device with my S6

### ISSUE THREAD

**Issue by dzean** [don/BluetoothLock#1]
Hi Don,
First of all thanks for sharing your experience...

I tried the [BluetoothLock tutorial](http://makezine.com/projects/controlling-a-lock-with-an-arudino-and-bluetooth-le/).

When I am using Bluefruit LE app, I can see UART device, connect to it and send data to unlock.
But when I am using the cordova app on my Android device (Samsung S6 phone), the BluetoothSerial.list doesn't list the UART device.

Worse, When I go to Bluetooth phone parameters, I see UART device but when I click on it, it tells me that it is impossible de associate it with my phone.

I have also tested this : https://github.com/don/cordova-plugin-ble-central
This is working even if there is delay with communication.

Any idea or advice to help me with unlock project ?

Thanks
Jean

**Comment by dzean** [comment]
I used the https://github.com/don/cordova-plugin-ble-central/tree/master/examples/bluefruitle code and I can now connect to the Bluetooth LE ship on the arduino.

But now I have a new problem : I have an error after the resertLock instruction, only if I plug the solenoid to the arduino : ERROR: [object Object]

I have tested with 2 different kind of solenoid : 
1) http://www.ebay.fr/itm/FC-MXBB-DC-12V-0-6A-Cabinet-Door-Electric-Lock-Assembly-Solenoid-/322182831910?hash=item4b0397df26:g:UWAAAOSw7XZXiBsk
2) http://www.ebay.fr/itm/282065331755?euid=f38a3215241648ba89ce2cab13a59d5d&bu=43925733887&cp=1&sojTags=bu=bu

An odd thing is that with number 2, I have the error only if I out the metal bar in the solenoid. If not = no error.
This is due to electric problem no ?

thanks

**Comment by don** [comment]
It sounds like you have an electrical problem. Solenoids draw a lot of power and it might be causing Bluetooth to disconnect. Are you using a separate power supply for the solenoid?

Try JSON.stringify on the object that was [Object object]. Most likely it's going to be the peripheral info for the object that disconnected.
